# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  center.gdzc.com:
    container_name: center.gdzc.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - ORDERER_GENERAL_LOGLEVEL=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/gdzc.com/orderers/center.gdzc.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/gdzc.com/orderers/center.gdzc.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  hello.node1.gdzc.com:
    container_name: hello.node1.gdzc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=hello.node1.gdzc.com
      - CORE_PEER_ADDRESS=hello.node1.gdzc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=word.node1.gdzc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=hello.node1.gdzc.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/node1.gdzc.com/peers/hello.node1.gdzc.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/node1.gdzc.com/peers/hello.node1.gdzc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053

  word.node1.gdzc.com:
    container_name: word.node1.gdzc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=word.node1.gdzc.com
      - CORE_PEER_ADDRESS=word.node1.gdzc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=word.node1.gdzc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=hello.node1.gdzc.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/node1.gdzc.com/peers/word.node1.gdzc.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/node1.gdzc.com/peers/word.node1.gdzc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053

  zhao.node2.gdzc.com:
    container_name: zhao.node2.gdzc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=zhao.node2.gdzc.com
      - CORE_PEER_ADDRESS=zhao.node2.gdzc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=zhao.node2.gdzc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=weixiong.node2.gdzc.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/node2.gdzc.com/peers/zhao.node2.gdzc.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/node2.gdzc.com/peers/zhao.node2.gdzc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9053:7053

  weixiong.node2.gdzc.com:
    container_name: weixiong.node2.gdzc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=weixiong.node2.gdzc.com
      - CORE_PEER_ADDRESS=weixiong.node2.gdzc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=weixiong.node2.gdzc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=zhao.node2.gdzc.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/node2.gdzc.com/peers/weixiong.node2.gdzc.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/node2.gdzc.com/peers/weixiong.node2.gdzc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 10051:7051
      - 10053:7053

  peer0.node3.gdzc.com:
    container_name: peer0.node3.gdzc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.node3.gdzc.com
      - CORE_PEER_ADDRESS=peer0.node3.gdzc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.node3.gdzc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.node3.gdzc.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/node3.gdzc.com/peers/peer0.node3.gdzc.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/node3.gdzc.com/peers/peer0.node3.gdzc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11053:7053

  peer1.node3.gdzc.com:
    container_name: peer1.node3.gdzc.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.node3.gdzc.com
      - CORE_PEER_ADDRESS=peer1.node3.gdzc.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.node3.gdzc.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.node3.gdzc.com:7051
      - CORE_PEER_LOCALMSPID=Org3MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/node3.gdzc.com/peers/peer1.node3.gdzc.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/node3.gdzc.com/peers/peer1.node3.gdzc.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 12051:7051
      - 12053:7053
