# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  byfn:

services:

  center.gdzc.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: center.gdzc.com
    container_name: center.gdzc.com
    networks:
      - byfn

  hello.node1.gdzc.com:
    container_name: hello.node1.gdzc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: hello.node1.gdzc.com
    networks:
      - byfn

  word.node1.gdzc.com:
    container_name: word.node1.gdzc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: word.node1.gdzc.com
    networks:
      - byfn

  zhao.node2.gdzc.com:
    container_name: zhao.node2.gdzc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: zhao.node2.gdzc.com
    networks:
      - byfn

  weixiong.node2.gdzc.com:
    container_name: weixiong.node2.gdzc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: weixiong.node2.gdzc.com
    networks:
      - byfn

  peer0.node3.gdzc.com:
      container_name: peer0.node3.gdzc.com
      extends:
        file:  base/docker-compose-base.yaml
        service: peer0.node3.gdzc.com
      networks:
        - byfn

  peer1.node3.gdzc.com:
    container_name: peer1.node3.gdzc.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.node3.gdzc.com
    networks:
      - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=hello.node1.gdzc.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/node1.gdzc.com/peers/hello.node1.gdzc.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/node1.gdzc.com/peers/hello.node1.gdzc.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/node1.gdzc.com/peers/hello.node1.gdzc.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/node1.gdzc.com/users/Admin@node1.gdzc.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - center.gdzc.com
      - hello.node1.gdzc.com
      - word.node1.gdzc.com
      - zhao.node2.gdzc.com
      - weixiong.node2.gdzc.com
      - peer0.node3.gdzc.com
      - peer1.node3.gdzc.com
    networks:
      - byfn
